// Generated by node scripts/update-command-catalog.cjs; do not edit by hand.
(() => {
  const catalog = {
    text: [
      {"id":"format-json","name":"Format JSON","description":"Clean and indent JSON","category":"Popular","icon":"{ }","tags":"json pretty clean indent","file":"format-json.js"},
      {"id":"base64-encode","name":"Base64 encode","description":"Encode text as Base64","category":"Popular","icon":"64","tags":"base64 encode","file":"base64-encode.js"},
      {"id":"url-encode","name":"URL encode","description":"Make text URL-safe","category":"Popular","icon":"%","tags":"url uri encode","file":"url-encode.js"},
      {"id":"uppercase","name":"UPPERCASE","description":"Convert every character","category":"Popular","icon":"AA","tags":"upper case capitals","file":"uppercase.js"},
      {"id":"ascii-hex","name":"ASCII to hex","description":"Encode text as hexadecimal","category":"Encoding","icon":"0x","tags":"ascii hex encode","file":"ascii-hex.js"},
      {"id":"base64-decode","name":"Base64 decode","description":"Decode Base64 into text","category":"Encoding","icon":"64","tags":"base64 decode","file":"base64-decode.js"},
      {"id":"binary-decimal","name":"Binary to decimal","description":"Convert base 2 to base 10","category":"Numbers","icon":"10","tags":"binary decimal number","file":"binary-decimal.js"},
      {"id":"camel-case","name":"camelCase","description":"Join words in camel case","category":"Case","icon":"cC","tags":"camel case","file":"camel-case.js"},
      {"id":"collapse","name":"Collapse whitespace","description":"Replace whitespace with spaces","category":"Text","icon":"⇥","tags":"collapse whitespace spaces","file":"collapse.js"},
      {"id":"count","name":"Count text","description":"Show characters, words, and lines","category":"Text","icon":"#","tags":"count words characters lines","file":"count.js"},
      {"id":"csv-json","name":"CSV to JSON","description":"Turn a CSV table into objects","category":"JSON & data","icon":"↔","tags":"csv json convert","file":"csv-json.js"},
      {"id":"date-timestamp","name":"Date to timestamp","description":"Convert a date to Unix seconds","category":"Numbers","icon":"⌚","tags":"date timestamp unix time","file":"date-timestamp.js"},
      {"id":"decimal-binary","name":"Decimal to binary","description":"Convert base 10 to base 2","category":"Numbers","icon":"01","tags":"decimal binary number","file":"decimal-binary.js"},
      {"id":"decimal-hex","name":"Decimal to hex","description":"Convert base 10 to base 16","category":"Numbers","icon":"0x","tags":"decimal hex number","file":"decimal-hex.js"},
      {"id":"dedupe-lines","name":"Remove duplicate lines","description":"Keep the first of each line","category":"Text","icon":"≠","tags":"duplicate unique lines dedupe","file":"dedupe-lines.js"},
      {"id":"epoch-now","name":"Generate epoch timestamp","description":"Insert the current Unix epoch in seconds","category":"Numbers","icon":"NOW","tags":"epoch timestamp unix current now integer int seconds","file":"epoch-now.js"},
      {"id":"hex-ascii","name":"Hex to ASCII","description":"Decode hexadecimal bytes","category":"Encoding","icon":"0x","tags":"hex ascii decode","file":"hex-ascii.js"},
      {"id":"hex-decimal","name":"Hex to decimal","description":"Convert base 16 to base 10","category":"Numbers","icon":"10","tags":"hex decimal number","file":"hex-decimal.js"},
      {"id":"html-decode","name":"HTML decode","description":"Decode HTML entities","category":"Encoding","icon":"<>","tags":"html entities unescape decode","file":"html-decode.js"},
      {"id":"html-encode","name":"HTML encode","description":"Escape HTML entities","category":"Encoding","icon":"<>","tags":"html entities escape encode","file":"html-encode.js"},
      {"id":"json-csv","name":"JSON to CSV","description":"Turn object rows into CSV","category":"JSON & data","icon":"↔","tags":"json csv convert","file":"json-csv.js"},
      {"id":"json-query","name":"JSON to query string","description":"Build URL query parameters","category":"JSON & data","icon":"=?","tags":"json query url params","file":"json-query.js"},
      {"id":"jwt-decode","name":"Decode JWT","description":"Read a JWT header and payload","category":"Security","icon":"JWT","tags":"jwt token decode security","file":"jwt-decode.js"},
      {"id":"kebab-case","name":"kebab-case","description":"Join words with hyphens","category":"Case","icon":"k-k","tags":"kebab case hyphen","file":"kebab-case.js"},
      {"id":"lorem","name":"Lorem ipsum","description":"Insert a sample paragraph","category":"Text","icon":"Li","tags":"lorem ipsum placeholder","file":"lorem.js"},
      {"id":"lowercase","name":"lowercase","description":"Convert every character","category":"Case","icon":"aa","tags":"lower down case","file":"lowercase.js"},
      {"id":"markdown-quote","name":"Markdown quote","description":"Prefix every line with >","category":"Text","icon":">_","tags":"markdown quote blockquote","file":"markdown-quote.js"},
      {"id":"minify-json","name":"Minify JSON","description":"Remove JSON whitespace","category":"JSON & data","icon":"{}","tags":"json minify compress","file":"minify-json.js"},
      {"id":"query-json","name":"Query string to JSON","description":"Parse URL query parameters","category":"JSON & data","icon":"?=","tags":"query url json params","file":"query-json.js"},
      {"id":"reverse-lines","name":"Reverse lines","description":"Flip line order","category":"Text","icon":"↕","tags":"reverse lines order","file":"reverse-lines.js"},
      {"id":"reverse-string","name":"Reverse text","description":"Flip character order","category":"Text","icon":"↔","tags":"reverse string text","file":"reverse-string.js"},
      {"id":"rot13","name":"ROT13","description":"Rotate letters by 13 places","category":"Encoding","icon":"R13","tags":"rot13 cipher","file":"rot13.js"},
      {"id":"sample-json","name":"Insert sample JSON","description":"Load a small array of objects","category":"JSON & data","icon":"[ ]","tags":"sample example json array objects insert starter","file":"sample-json.js"},
      {"id":"sha1","name":"SHA-1","description":"Create a SHA-1 digest","category":"Security","icon":"S1","tags":"sha1 hash digest","file":"sha1.js"},
      {"id":"sha256","name":"SHA-256","description":"Create a SHA-256 digest","category":"Security","icon":"S2","tags":"sha256 hash digest","file":"sha256.js"},
      {"id":"sha512","name":"SHA-512","description":"Create a SHA-512 digest","category":"Security","icon":"S5","tags":"sha512 hash digest","file":"sha512.js"},
      {"id":"shuffle-lines","name":"Shuffle lines","description":"Randomize line order","category":"Text","icon":"⇄","tags":"shuffle random lines","file":"shuffle-lines.js"},
      {"id":"smart-quotes","name":"Replace smart quotes","description":"Normalize curly quotation marks","category":"Text","icon":"“”","tags":"smart quotes apostrophe replace","file":"smart-quotes.js"},
      {"id":"snake-case","name":"snake_case","description":"Join words with underscores","category":"Case","icon":"s_s","tags":"snake case underscore","file":"snake-case.js"},
      {"id":"sort-json","name":"Sort JSON keys","description":"Alphabetize keys recursively","category":"JSON & data","icon":"AZ","tags":"json sort keys alphabetize","file":"sort-json.js"},
      {"id":"sort-lines","name":"Sort lines","description":"Alphabetize lines","category":"Text","icon":"AZ","tags":"sort lines alphabetize","file":"sort-lines.js"},
      {"id":"sponge-case","name":"sPoNgE cAsE","description":"Alternate letter casing","category":"Case","icon":"aA","tags":"sponge alternating case","file":"sponge-case.js"},
      {"id":"timestamp-date","name":"Timestamp to UTC","description":"Convert Unix seconds to a date","category":"Numbers","icon":"UTC","tags":"timestamp date unix utc time","file":"timestamp-date.js"},
      {"id":"title-case","name":"Start Case","description":"Capitalize each word","category":"Case","icon":"Aa","tags":"title start case","file":"title-case.js"},
      {"id":"trim","name":"Trim","description":"Remove surrounding whitespace","category":"Text","icon":"⌁","tags":"trim whitespace clean","file":"trim.js"},
      {"id":"url-decode","name":"URL decode","description":"Decode URL-safe text","category":"Encoding","icon":"%","tags":"url uri decode","file":"url-decode.js"},
      {"id":"url-defang","name":"Defang URL","description":"Make URLs safe to share","category":"Encoding","icon":"[.]","tags":"url defang security","file":"url-defang.js"},
      {"id":"url-refang","name":"Refang URL","description":"Restore a defanged URL","category":"Encoding","icon":".","tags":"url refang security","file":"url-refang.js"},
    ],
    sheet: [
      {"id":"average","name":"Average values","description":"Calculate the mean of the selected numeric cells","category":"Summary","icon":"AVG","tags":"average mean arithmetic","file":"cells/average.js"},
      {"id":"count","name":"Count numbers","description":"Count numeric cells in the selection","category":"Summary","icon":"#","tags":"count numbers numeric cells","file":"cells/count.js"},
      {"id":"divide","name":"Divide values","description":"Divide the first selected number by each following number","category":"Arithmetic","icon":"÷","tags":"divide quotient ratio","file":"cells/divide.js"},
      {"id":"maximum","name":"Maximum value","description":"Find the largest selected number","category":"Summary","icon":"MAX","tags":"maximum max largest high","file":"cells/maximum.js"},
      {"id":"minimum","name":"Minimum value","description":"Find the smallest selected number","category":"Summary","icon":"MIN","tags":"minimum min smallest low","file":"cells/minimum.js"},
      {"id":"multiply","name":"Multiply values","description":"Multiply every numeric cell in the selection","category":"Arithmetic","icon":"×","tags":"multiply product times","file":"cells/multiply.js"},
      {"id":"subtract","name":"Subtract values","description":"Subtract each selected number from the first","category":"Arithmetic","icon":"−","tags":"subtract minus difference","file":"cells/subtract.js"},
      {"id":"sum","name":"Add values","description":"Add every numeric cell in the selection","category":"Arithmetic","icon":"+","tags":"sum total add plus","file":"cells/sum.js"},
    ],
  };
  Object.values(catalog).forEach((commands) => {
    commands.forEach((command) => {
      command.searchText = [command.name, command.description, command.tags, command.category].join(" ").toLowerCase();
      Object.freeze(command);
    });
    Object.freeze(commands);
  });
  globalThis.ScratchpadCommandCatalog = Object.freeze(catalog);
})();
